const ConversationActionTypes = {
    GET_ALL_CONVERSATIONS_START: 'GET_ALL_CONVERSATIONS_START',
    GET_ALL_CONVERSATIONS_SUCCESS: 'GET_ALL_CONVERSATIONS_SUCCESS',
    GET_ALL_CONVERSATIONS_FAILURE: 'GET_ALL_CONVERSATIONS_FAILURE',
    SET_CHATTING_WITH: 'SET_CHATTING_WITH'
};

export default ConversationActionTypes;