const ConversationActionTypes = {
    GET_ALL_CONVERSATIONS_START: 'GET_ALL_CONVERSATIONS_START',
    GET_ALL_CONVERSATIONS_SUCCESS: 'GET_ALL_CONVERSATIONS_SUCCESS',
    GET_ALL_CONVERSATIONS_FAILURE: 'GET_ALL_CONVERSATIONS_FAILURE',
    CREATE_CONVERSATION_START: 'CREATE_CONVERSATION_START',
    CREATE_CONVERSATION_SUCCESS: 'CREATE_CONVERSATION_SUCCESS',
    CREATE_CONVERSATION_FAILURE: 'CREATE_CONVERSATION_FAILURE',
    SET_CHATTING_WITH: 'SET_CHATTING_WITH',
    BLOCK_USER_START: 'BLOCK_USER_START',
    BLOCK_USER_SUCCESS: 'BLOCK_USER_SUCCESS',
    BLOCK_USER_FAILURE: 'BLOCK_USER_FAILURE',
};

export default ConversationActionTypes;