const ConversationActionTypes = {
    GET_ALL_CONVERSATIONS_START: 'GET_ALL_CONVERSATIONS_START',
    GET_ALL_CONVERSATIONS_SUCCESS: 'GET_ALL_CONVERSATIONS_SUCCESS',
    GET_ALL_CONVERSATIONS_FAILURE: 'GET_ALL_CONVERSATIONS_FAILURE',
};

export default ConversationActionTypes;