const MessageActionTypes = {
    GET_MESSAGES_START: 'GET_MESSAGES_START',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',
    SEND_MESSAGE_START: 'SEND_MESSAGE_START',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
};

export default MessageActionTypes;