const UserActionTypes = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    CONTINUE_WITH_GOOGLE_START: 'CONTINUE_WITH_GOOGLE_START',
    CONTINUE_WITH_GOOGLE_SUCCESS: 'CONTINUE_WITH_GOOGLE_SUCCESS',
    CONTINUE_WITH_GOOGLE_FAILURE: 'CONTINUE_WITH_GOOGLE_FAILURE',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    CLEAR_AUTH_PROGRESS_STATUS: 'CLEAR_AUTH_PROGRESS_STATUS',
    CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
    CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
    CHECK_USER_SESSION_FAILURE: 'CHECK_USER_SESSION_FAILURE'
};

export default UserActionTypes;