const UserActionTypes = {
    GET_USER_BY_EMAIL_START: 'GET_USER_BY_EMAIL_START',
    GET_USER_BY_EMAIL_SUCCESS: 'GET_USER_BY_EMAIL_SUCCESS',
    GET_USER_BY_EMAIL_FAILURE: 'GET_USER_BY_EMAIL_FAILURE',
    GET_USER_BY_ID_START: 'GET_USER_BY_ID_START',
    GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
    GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE'
};

export default UserActionTypes;