const UserActionTypes = {
    GET_USER_BY_EMAIL_START: 'GET_USER_BY_EMAIL_START',
    GET_USER_BY_EMAIL_SUCCESS: 'GET_USER_BY_EMAIL_SUCCESS',
    GET_USER_BY_EMAIL_FAILURE: 'GET_USER_BY_EMAIL_FAILURE',
    GET_USER_BY_ID_START: 'GET_USER_BY_ID_START',
    GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
    GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE',
    GET_ALL_USERS_START: 'GET_ALL_USERS_START',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',
    UPDATE_CONVERSATION_USERS: 'UPDATE_CONVERSATION_USERS'
};

export default UserActionTypes;